# Generated by Django 4.1.2 on 2024-02-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_credittransactionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
