# Generated by Django 4.1.2 on 2024-02-12 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_creditdepositrequest"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CreditDepositRequest",
            new_name="DepositRequest",
        ),
    ]
