# Generated by Django 4.1.2 on 2024-02-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_rename_creditdepositrequest_depositrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credittransactionlog",
            name="type",
            field=models.CharField(
                choices=[("DEPOSIT", "Deposit"), ("SALE", "Sale")], max_length=10
            ),
        ),
    ]
