# Generated by Django 4.1.2 on 2024-02-13 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_credittransactionlog_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credittransactionlog",
            name="credit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_logs",
                to="store.credit",
            ),
        ),
        migrations.AlterField(
            model_name="depositrequest",
            name="credit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposit_requests",
                to="store.credit",
            ),
        ),
    ]
