# Generated by Django 4.1.2 on 2024-02-13 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_sale"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DepositRequest",
            new_name="Deposit",
        ),
    ]
