# Generated by Django 4.1.2 on 2024-02-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_rename_depositrequest_deposit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="store.seller",
            ),
        ),
    ]
